#!/usr/bin/env bash
# Bash script to display info on subdomains.

domain="$1"
SUBDOMAINS="www lb-01 web-01 web-02"

function show_info() {
    local subdomain="$1"
    echo -n "The subdomain $subdomain is a "
    dig "$subdomain.$domain" | grep -A1 'ANSWER SECTION:' | tail -n1 | awk '{print $4 " record and points to " $5}'
}

function show_all() {
    for subdomain in $SUBDOMAINS
    do
        show_info "$subdomain"
    done
}

if [ $# -eq 2 ]; then
    show_info "$2"
else
    show_all
fi
