#!/usr/bin/env bash
# A script that transfer a file
# from client -> server

if [ $# -lt 4 ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi

path_file=$1
ip=$2
username=$3
path_ssh_key=$4

#Disable strict host key for scp
scp -o "StrictHostKeyChecking=no" -i "$path_ssh_key" "$path_file" "$username@ip:~/"

if [ $? -eq 0 ]
then
	echo "Transfer Completed"
else
	echo "Transfer Failed"
fi
