#!/usr/bin/env bash
# Script to install nginx on my web server

sudo apt-get update
sudo apt-get install nginx
sudo ufw "Nginx HTTP"

# Set up index file
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo nginx -t
sudo service nginx reload
