#!/usr/bin/env bash
# 9. Process and PID file

# Create the file /var/run/myscript.pid containing its PID
echo $$ > /var/run/myscript.pid

# Function to handle SIGTERM and SIGQUIT signals
function cleanup {
    rm /var/run/myscript.pid
    exit 0
}

# Function to handle SIGINT signal
function handle_sigint {
    echo "Y U no love me?!"
}

# Function to handle SIGTERM signal
function handle_sigterm {
    echo "I hate the kill command"
}

# Register signal handlers
trap handle_sigint SIGINT
trap handle_sigterm SIGTERM
trap cleanup SIGQUIT SIGTERM

# Display "To infinity and beyond" indefinitely
while true
do
    echo "To infinity and beyond"
    sleep 1
done

