#!/usr/bin/env bash
# Write a Bash script that displays the PID, 
# along with the process name, 
# of processes whose name contain the word bash.

pgrep bash | xargs -I{} sh -c "echo {} $(ps -p {} -o comm=)"
