#!/usr/bin/env bash
# Write a Bash script that displays the content of the file /etc/passwd

while IFS=: read -r user passwd uid gid full_name home shell
do
    echo "$user $uid $home"
done < /etc/passwd
