#!/usr/bin/env bash
# Nginx must be running as nginx user

# Stop prcess
pkill -f apache2

# change owner
chown nginx:nginx /etc/nginx/nginx.conf

# Change permission
chmod 700 /etc/nginx/nginx.conf

# nginx must be listening on port 8080
sed -i 's/80 default_server/8080 default_server/' /etc/nginx/sites-available/default

# restart nginx with the prev config
sudo -u nginx service nginx start
