#!/usr/bin/env bash
# nginx must be running as nginx use

# Update the nginx configuration to run as the nginx user
sed -i 's/user\s*nginx;/user nginx;/' /etc/nginx/nginx.conf

# Update the nginx default site configuration to listen on port 8080
sed -i 's/listen\s*80;/listen 8080;/' /etc/nginx/sites-available/default

# Restart the nginx service to apply the changes
service nginx restart

# Verify that nginx is running as the nginx user and listening on port 8080
ps auxff | grep ngin[x]
nc -z 0 8080
