#!/usr/bin/env bash
# nginx must be running as nginx use
sed -i 's/user\s*nginx;/user nginx;/' /etc/nginx/nginx.conf
sed -i 's/listen\s*80;/listen 8080;/' /etc/nginx/sites-available/default
service nginx restart
ps auxff | grep ngin[x]
nc -z 0 8080
